name: Monitor de Editais

on:
  schedule:
    # Roda a cada 2 horas (cron job)
    - cron: '0 */2 * * *'
  
  # Aqui criamos o botão com OPÇÕES
  workflow_dispatch:
    inputs:
      modo_teste:
        description: 'ATIVAR MODO TESTE? (Ignora histórico e pega 24h)'
        required: false
        default: false
        type: boolean

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar Dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar o Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          MEU_CHAT_ID: ${{ secrets.MEU_CHAT_ID }}
          # Aqui passamos a opção que você marcou para o Python
          MODO_TESTE: ${{ github.event.inputs.modo_teste }}
        run: python bot.py
